---
- hosts: web
  become: true
  tasks:
    - name: Install podman and nginx
      ansible.builtin.dnf:
        name:
          - podman
          - nginx
        state: present
    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    - name: Pull backend image from quay.io
      containers.podman.podman_image:
        name: quay.io/arnevcrs/microservice-movies:latest
        pull: true
        state: present
    - name: Run movies backend container
      containers.podman.podman_container:
        name: microservice-movies-backend
        image: quay.io/arnevcrs/microservice-movies:latest
        state: started
        detach: true
        publish:
          - '8080:80' 
        restart_policy: always
    - name: Pull Postgres image
      containers.podman.podman_image:
        name: docker.io/library/postgres:14
        pull: true
        state: present
    - name: Ensure Postgres data directory exists
      ansible.builtin.file:
        path: /var/lib/microservice-movies/postgres
        state: directory
        owner: root
        group: root
        mode: '0700'
    - name: Run Postgres container (no auth)
      containers.podman.podman_container:
        name: microservice-postgres
        image: docker.io/library/postgres:14
        state: started
        detach: true
        publish:
          - '5000:5432'
        restart_policy: always
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
          - /var/lib/microservice-movies/postgres:/var/lib/postgresql/data:Z
    - name: Create frontend archive on controller
      ansible.builtin.command:
        cmd: tar -C "{{ playbook_dir }}/st-microservice-frontend" -cf /tmp/st-microservice-frontend.tar .
      delegate_to: localhost
      run_once: true

    - name: Copy frontend archive to remote
      ansible.builtin.copy:
        src: /tmp/st-microservice-frontend.tar
        dest: /tmp/st-microservice-frontend.tar
        mode: '0644'

    - name: Extract frontend archive on remote into nginx web root
      ansible.builtin.unarchive:
        src: /tmp/st-microservice-frontend.tar
        dest: /usr/share/nginx/html/
        remote_src: yes
        extra_opts:
          - "--no-same-owner"
      register: frontend_deploy

    - name: Remove remote frontend archive
      ansible.builtin.file:
        path: /tmp/st-microservice-frontend.tar
        state: absent

    - name: Remove controller frontend archive
      ansible.builtin.file:
        path: /tmp/st-microservice-frontend.tar
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Ensure correct SELinux context on nginx web root (if SELinux enabled)
      ansible.builtin.command:
        cmd: restorecon -R -v /usr/share/nginx/html || true
      changed_when: false

    - name: Restart nginx if frontend changed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: frontend_deploy.changed